name: Supabase Heartbeat

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -L -X POST 'https://mkjsgiwhmhvmkqmzbhqt.supabase.co/functions/v1/send_heartbeat' \
            -H 'Authorization: Bearer sb_publishable_TIHkvV7Ntlotd0pbcJImpg_FuOPLbFe' \
            -H 'apikey: sb_publishable_TIHkvV7Ntlotd0pbcJImpg_FuOPLbFe' \
            -H 'Content-Type: application/json' \
            --data '{"name":"Functions"}'
