name: Supabase Heartbeat

# Ex√©cution automatique toutes les 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # permet de lancer manuellement

jobs:
  call-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Function
        run: |
          curl -X GET "https://mkjsgiwhmhvmkqmzbhqt.functions.supabase.co/send_heartbeat" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
